### ISSUE TITLE
["Problem"] references need to be moved

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/NIH_Data_Sharing#19]
References got moved to after session info section... need to fix that

**Comment by avahoffman** [comment]
Does OTTR assume "References" is the last Rmd?

**Comment by carriewright11** [comment]
yes - I moved it so it should be OK now - I just added to your PR

**Comment by carriewright11** [comment]
I think I am the one that messed it up but I can't remember :P

**Comment by carriewright11** [comment]
> Does OTTR assume "References" is the last Rmd?

I think we need to explain that better in the documentation - we could also try to make it more flexible in the future

**Comment by carriewright11** [comment]
I made an issue on our template

**Comment by carriewright11** [comment]
and now I added to our documentation :)
