### ISSUE TITLE
Create links from the "key questions" overview in "Will this policy affect me?" chapter

### ISSUE THREAD

**Issue by ehumph** [fhdsl/NIH_Data_Sharing#25]
At the beginning of the chapter, there is this snippet:

The following outline several key questions:

**Is my research exempt from the policy?**
**Does my research generate scientific data?** If yes, you will need to submit a DMS Plan.
**When do I need to share my data?**
**Can I elect to not share data?** The short answer is yes. However, you must still justify this choice in a submitted DMS Plan.

Might be helpful to make each question a link to the subsection that addresses the answer.

**Comment by carriewright11** [comment]
I like this idea!

**Comment by avahoffman** [comment]
nice!
