### ISSUE TITLE
Ethics section

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/NIH_Data_Sharing#27]
We are interested in at least pointing out concerns that people should think about.
- many clinical considerations for sharing data
    - people need to be careful with de-identification and should ideally work with an expert
- in terms of raw vs cleaned data -what level of effort/funding/resources should be used to make data easy for someone to use the data from scratch, since slightly processed data while less convenient takes up less space/uses less resources

- what quality threshold is really needed to share data? 
    - what are the consequences of sharing poor-quality data? 
    - what are the consequences of not sharing data that is of reasonable quality that someone decided was poor quality?

**Comment by carriewright11** [comment]
@vortexing , @avahoffman , @ehumph please feel free to add your thoughts here or I can move this to basecamp if that is better

**Comment by avahoffman** [comment]
How much does the new policy go into this? I wonder if this is something we should "refer people out to" ? I just want to make sure we're not overstepping at all.

**Comment by ehumph** [comment]
I do think at least the de-identification issue needs to be at least mentioned, especially since being unable to remove PHI is one of the reasons for not sharing data. I know everyone is supposed to go through the training, so maybe there can be a sentence about it and then a link to the Fred Hutch course?

As for the other stuff - I mean, it's pretty important and I feel like NIH kind of glossed over these questions. Ava, would you feel more comfortable if we added those to the list of questions for Jeff to ask?

**Comment by vortexing** [comment]
You don't technically have to de-identify data in order to share it.  You just need to go through the process with the IRB and consent review to identify under what conditions the data CAN be shared.  Those conditions may be very limiting but usually are not full "cannot be shared" restrictions.

**Comment by carriewright11** [comment]
I like the idea of talking to Jeff about this. I agree that we don't want to overstep, but I do want to be responsible in how we suggest people share data. I think we could also make these points as open-ended questions without answers- as it isn't yet clear what the answers would be - to reduce overstepping maybe?

**Comment by avahoffman** [comment]
Totally agree that we need to address this. I am mostly concerned about a "DaSL said it was okay" situation. As long as we're mindful of that, I think we're good :)

**Comment by carriewright11** [comment]
https://elsihub.org/

**Comment by carriewright11** [comment]
What if we made this part of the appendix or a chapter at the end where we just pose everything as questions and it could be really cool if we opened it up to people on the google form and we could post curated comments and questions or something? just throwing out ideas here :P

**Comment by ehumph** [comment]
> What if we made this part of the appendix or a chapter at the end where we just pose everything as questions and it could be really cool if we opened it up to people on the google form and we could post curated comments and questions or something? just throwing out ideas here :P @avahoffman, @vortexing, @ehumph @jtleek what do you think?

I do like this idea! Even if we don't open it up to other people, the appendix feels like the right place for it.

**Comment by avahoffman** [comment]
Agree. Let's add to the appendix, and we can link to it from the relevant sections throughout the course.
