### ISSUE TITLE
Source some average `fcs` file sizes

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/NIH_Data_Sharing#37]
can we source some average `fcs` file sizes? I can post a message in the slack.

_Originally posted by @avahoffman in https://github.com/fhdsl/NIH_Data_Sharing/pull/34#discussion_r1012397370_
      

A response from Slack:

> In our lab it varies by project but usually 1-50 MB each, with the averages ranging from 2 - 20MB

**Comment by ehumph** [comment]
@avahoffman I think we might just want to put 1-50 MB in the table.
