### ISSUE TITLE
Grant threshold 500,000

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/NIH_Data_Sharing#46]
Is there a threshold requirement for compliance, think I read that.

**Comment by vortexing** [comment]
It used to be only for $500k and above, but that is ending in 2023, so now it applies to:
"This includes all NIH-supported research regardless of funding level, including: extramural grants, extramural contracts, intramural research projects, and other funding agreements."

so "Regardless of funding level".  That's the bummer.  There are a number of folks who never have grants this big so they never have had to deal with this before.
