### ISSUE TITLE
add a TLDR summary to beginning

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/NIH_Data_Sharing#66]
Jeff said he didn't see the review process section - so  he suggested adding this

**Comment by carriewright11** [comment]
he suggested the top 6 major things or something - maybe a graphic for the beginning?- or it could at least say what questions we cover?

He wants to include the fact that the DMS will not be part of the review process

**Comment by carriewright11** [comment]
my thoughts on things to maybe  include - as a question or statement:
- Do you have to share data
- Can you change your plan
- Can you request money for storage costs
- Is the DMS plan part of the review process 
- When do you have to share data
- What if I can't find a repository

**Comment by carriewright11** [comment]
@avahoffman  @ehumph @vortexing what do you think?

**Comment by avahoffman** [comment]
> my thoughts on things to maybe include - as a question or statement:
> 
>     Do you have to share data
>     Can you change your plan
>     Can you request money for storage costs
>     Is the DMS plan part of the review process
>     When do you have to share data
>     What if I can't find a repository

I kind of like these in the FAQ. What do you think about the TLDR super briefly reflecting the book sections:

1. Why this change
   - transparency, reproducibility
2. Does this apply to me?
   - Some grant mechanisms are exempt
   - Some data is exempt from sharing requirements
3. Data management and storage
   - NIH lists suggested repositories. You should find one most appropriate for your work
4. Budgeting
   - Allowable, unallowable
5. Sections in your proposal
6. Submission
   - Remember your plan is not going to effect your review/evaluation

**Comment by ehumph** [comment]
I like the symmetry of including all the book sections, but worry it might create too much of a wall of words. Can the TLDR be just a quick outline? If it needs to be actually written, then I think we might want to pare it down to something like:

"As of January 23, 2023, the NIH is requiring all grant proposals include a Data Management and Sharing Plan. This will apply to most grants that create data, although some grant mechanisms and some data are exempt from the new sharing requirements. The NIH has lists of suggested repositories, but you will need to choose the one most appropriate for your work. You may request funds for your data management plan that specifically covers the direct costs of wrangling and depositing the data. You may _not_ include indirect costs associated with managing and storing the data. Your Data Management and Sharing Plan should be no longer than 2 pages and include sections on data type; tools, software, and code; standards; data preservation, access, and timelines; access, distribution, and reuse considerations; and oversight. Although the Data Management and Sharing Plan is a mandatory part of most grant proposals, it will not effect the review and evaluation of your grant."

**Comment by avahoffman** [comment]
@ehumph Yes, I think we need to be careful that it's super brief. I wasn't imagining more than a sentence or so under 1-6

**Comment by ehumph** [comment]
@avahoffman excellent. Then maybe...

1. **Why this change**: As of January 23, 2023, the NIH is requiring all grant proposals include a Data Management and Sharing Plan to aid in transparency and reproducibility of NIH-funded research. 
2. **Does this apply to me?** This will apply to most grants that create data, although some grant mechanisms and some data are exempt from the new sharing requirements. 
3. **What should I use for data management and storage?** The NIH has lists of suggested repositories, but you will need to choose the one most appropriate for your work. 
4. **What are budgeting requirement?** You may request funds for your data management plan that specifically covers the direct costs of wrangling and depositing the data. You may not include indirect costs associated with managing and storing the data. 
5. **What are the formatting requirements?** Your Data Management and Sharing Plan should be no longer than 2 pages and include sections on data type; tools, software, and code; standards; data preservation, access, and timelines; access, distribution, and reuse considerations; and oversight. 
6. **How will this new requirement impact my grant score?** Although the Data Management and Sharing Plan is a mandatory part of most grant proposals, it will not effect the review and evaluation of your grant.

**Comment by avahoffman** [comment]
Love it!

**Comment by carriewright11** [comment]
me too!

**Comment by vortexing** [comment]
I like your list there Ava.  I'd add to #3 something about what to do when there isn't a public repository. My read for Hutch folks is they are likely far more able to create a plan w/o issue, but the anxiety is actually coming from whether they're going to be able to (and afford to) actually execute the plan.  

I like the TLDR too and agree to keep it short.

**Comment by carriewright11** [comment]
> I like your list there Ava. I'd add to #3 something about what to do when there isn't a public repository. My read for Hutch folks is they are likely far more able to create a plan w/o issue, but the anxiety is actually coming from whether they're going to be able to (and afford to) actually execute the plan.
> 
> I like the TLDR too and agree to keep it short.

Agreed that this seems really important.

**Comment by carriewright11** [comment]
I am going to try to make a graphic of the text

**Comment by carriewright11** [comment]
How is this? I kept most of the text from @ehumph but made it a tad shorter in certain spots to try to fit easier.

<img width="955" alt="Screen Shot 2022-11-10 at 11 36 10 AM" src="https://user-images.githubusercontent.com/23014755/201153860-99d493b9-da49-4723-843c-88fb2190b606.png">

**Comment by avahoffman** [comment]
I love it!! Any concerns with accessibility re: having this in graphic form vs. having it appear in text? This was an issue for some of the figures in the GDSCN manuscript.

**Comment by carriewright11** [comment]
Or how about a written version initially and this at the end? as a summary?

**Comment by avahoffman** [comment]
What about just the headers? And then the text below. 

Something liike this (But far less ugly). But honestly okay with whatever!

<img width="961" alt="image" src="https://user-images.githubusercontent.com/15618412/201179056-ef06e217-56aa-4feb-ba05-db4638c227ef.png">

**Comment by carriewright11** [comment]
yeah Amy and I talked about that- we thought that the graphic in general could be really useful for people to use - like tweets (if we are still doing that) and things

**Comment by carriewright11** [comment]
but maybe we could have two graphic versions

**Comment by carriewright11** [comment]
I also think we should maybe have some of the major points in the section that is the overview of the plan that have to do with writing it.

**Comment by avahoffman** [comment]
If we want to tweet them, I think we would probably do 6 of them separately in a twitter thread. Although is twitter going to be around much longer ? 😜😅

**Comment by avahoffman** [comment]
Here's how they could look split up:
<img width="885" alt="image" src="https://user-images.githubusercontent.com/15618412/201268524-521bcfee-f401-493c-b5b4-681663663f15.png">
<img width="864" alt="image" src="https://user-images.githubusercontent.com/15618412/201268556-b689afa3-1be7-4021-a7bd-282a5cfe1121.png">

**Comment by carriewright11** [comment]
OK sounds good - I made a text version in the course for the PR. I also made the rest of the separate slides.

**Comment by avahoffman** [comment]
Awesome, this is looking great!
