### ISSUE TITLE
share some of the NIH knowledge

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/NIH_Data_Sharing#67]
Jeff wanted us to add info about how NIH doesn't have specific expectations and knows that they will learn from this process

**Comment by carriewright11** [comment]
maybe telling people to be mindful of what they think they can actually do and not overstate what they can do

**Comment by ehumph** [comment]
Has the NIH made an official statement about not having specific expectations and learning from the process? I wonder if we could get in trouble if it's only an unofficial comment that we have made public.

Would this go under a section at the end called "Final Considerations" or something?

**Comment by carriewright11** [comment]
I like the way you worded it @ehumph! Indeed I do think we want to be careful. We could see what @jtleek thinks about this

**Comment by carriewright11** [comment]
I am asking him on basecamp

**Comment by carriewright11** [comment]
Jeff says he likes it

**Comment by carriewright11** [comment]
Now just to figure out where to put it... under the takeaways?

**Comment by ehumph** [comment]
Maybe? Possibly right after the TLDR summary as well.
