### ISSUE TITLE
Form feedback goes where?

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/NIH_Data_Sharing#75]
Just wondering how this was set up and how to manage that

**Comment by carriewright11** [comment]
From Amy: Do any of these google forms send their outputs to this Slack channel? I thought someone did set that up to work but I'm not sure which forms do this. https://fhdata.slack.com/archives/C041DUC1TUJ

**Comment by avahoffman** [comment]
The file itself is in the Google Drive (DaSL Public > FH DSL > Feedback for FH DaSL Courses)

The google form sends an email to me and to data at fredhutch.org

<img width="491" alt="image" src="https://user-images.githubusercontent.com/15618412/201833537-81e18103-5036-411a-8f84-889f3f390ba2.png">

**Comment by vortexing** [comment]
Coolio!
