### ISSUE TITLE
links for Amy and Sandy for author section

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/NIH_Data_Sharing#77]
I'm not sure if @ehumph asked about this already.

@vortexing are you good with your linkedin being used for the author section?

We should see if Sandy is cool with us linking to the fredhutch team page.

**Comment by vortexing** [comment]
Yeah for now.  I need to do a little tune up of that aspect of things but I never seem to have time AND motivation to do it.

**Comment by carriewright11** [comment]
Thanks for asking Sandy!
