### ISSUE TITLE
FAQ link for NIH page

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/NIH_Data_Sharing#81]
from @vortexing on slack:

The [link](https://osp.od.nih.gov/scientific-sharing/nih-policy-for-data-management-and-sharing-faq/) to the DMS policy FAQ link listed here https://hutchdatascience.org/NIH_Data_Sharing/faq.html is broken.
Perhaps it should be https://sharing.nih.gov/faqs#/data-management-and-sharing-policy.htm?

**Comment by Rishav1707** [comment]
Shall I work on this issue?? @avahoffman

**Comment by avahoffman** [comment]
I think we've got it covered @Rishav1707 !

**Comment by Rishav1707** [comment]
> I think we've got it covered @Rishav1707 !

Ok then, close this issue😊
